TARGET_SPEED = 25.0
SAFETY_DISTANCE = 15.0
MAX_ACCELERATION = 2.0
MAX_DECELERATION = -3.0
DT = 0.1
MAX_SPEED = 35.0
MIN_SPEED = 0.0

EPISODE_LENGTH = 1000
OBSERVATION_DIM = 5
ACTION_DIM = 1

TRAINING_TIMESTEPS = 100000
SAVE_FREQUENCY = 10000
LOG_FREQUENCY = 1000
BATCH_SIZE = 64
GAMMA = 0.99
LEARNING_RATE = 3e-4
N_EPOCHS = 10
CLIP_RANGE = 0.2

MODEL_DIR = "models"
LOG_DIR = "logs"

TEST_EPISODES = 10
TEST_RENDER = True

REWARD_SPEED_WEIGHT = 1.0
REWARD_DISTANCE_WEIGHT = 1.5
REWARD_COMFORT_WEIGHT = 0.5
REWARD_EFFICIENCY_WEIGHT = 0.3
# ============ 传感器融合配置 ============
# 传感器权重配置
RADAR_WEIGHT = 0.4
CAMERA_WEIGHT = 0.3
LIDAR_WEIGHT = 0.3

# 传感器融合参数
FUSION_THRESHOLD = 0.5
MAX_DETECTION_DISTANCE = 200.0

# 雷达参数
RADAR_MAX_RANGE = 200.0
RADAR_FOV = 60.0

# 摄像头参数
CAMERA_MAX_RANGE = 150.0
CAMERA_FOV = 120.0

# 激光雷达参数
LIDAR_MAX_RANGE = 250.0
LIDAR_FOV = 120.0

# ============ 安全约束配置 ============
# 距离约束
MIN_SAFE_DISTANCE = 10.0
WARNING_DISTANCE = 20.0
CAUTION_DISTANCE = 30.0

# 速度约束
MAX_SPEED_LIMIT = 35.0
MIN_SPEED_LIMIT = 0.0

# 加速度约束
MAX_ACCELERATION_LIMIT = 2.0
MAX_DECELERATION_LIMIT = -5.0
COMFORTABLE_ACCELERATION = 1.5
COMFORTABLE_DECELERATION = -2.0

# TTC约束
TTC_DANGER_THRESHOLD = 3.0
TTC_WARNING_THRESHOLD = 5.0

# AEB参数
AEB_ENABLED = True
AEB_PARTIAL_BRAKING_DISTANCE = 30.0
AEB_FULL_BRAKING_DISTANCE = 15.0
AEB_PARTIAL_DECEL = -3.0
AEB_FULL_DECEL = -6.0

# ============ 模型轻量化配置 ============
# 剪枝参数
PRUNING_ENABLED = True
PRUNING_RATIO = 0.3
PRUNING_THRESHOLD = None

# 量化参数
QUANTIZATION_ENABLED = True
QUANTIZATION_TYPE = "dynamic"

# 知识蒸馏参数
DISTILLATION_ENABLED = False
DISTILLATION_TEMPERATURE = 3.0
DISTILLATION_ALPHA = 0.7

# 模型导出参数
EXPORT_FORMAT = "pytorch"
MODEL_SAVE_PATH = "models/optimized_acc_model.pt"

# 性能目标
TARGET_MODEL_SIZE_MB = 1.0
TARGET_INFERENCE_TIME_MS = 10.0

# ============ 其他配置 ============
HUTB_ENABLED = True
HUTB_HOST = "localhost"
HUTB_PORT = 8080
HUTB_TIMEOUT = 5.0
